name: covid19
description: A covid 19 application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 6.2.0+6.2.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  flutter_icons: ^1.0.0+1
  loading_animations: ^2.1.0
  cached_network_image: ^2.0.0
  fl_chart: ^0.11.0
  dio_http_cache: ^0.2.8
  intl: ^0.16.1
  bottom_navy_bar: ^5.5.0
  adaptive_theme: ^1.0.0
  shared_preferences: ^0.5.10
  url_launcher: ^5.5.2
  flutter_animator: ^2.1.0
  lottie: ^0.6.0
  latlong: ^0.6.1
  flutter_map: ^0.10.1+1
  geolocator: ^6.0.0
  hooks_riverpod: ^0.9.2
  flutter_hooks: ^0.14.0
  state_notifier: ^0.6.0
  flutter_dotenv: ^2.1.0
  list_tile_switch: ^0.0.2
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  flutter_native_admob: ^2.1.0+3
  flare_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  flutter_launcher_name: "^0.0.1"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/appicon.png"
  adaptive_icon_background: "assets/iconbg2.png"
  adaptive_icon_foreground: "assets/icon.png"

# flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/iconbg2.png
  color: "#452981"
  # fill: true
  # color: "0084ff"

# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "Covid 19 Tracker"
  # name: "korona"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/flar/
    - assets/lottiefiles/
    - json/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
